<script>
  import { createEventDispatcher } from 'svelte';
  import { proposalAPI } from '../lib/api.js';
  
  const dispatch = createEventDispatcher();
  
  let title = '';
  let summary = '';
  let cid = '';
  let confidence = 75;
  let metadata = '';
  let submitting = false;
  let error = null;
  
  // Example data for demo
  const exampleData = {
    title: "Investment Memo: NexGenAI",
    summary: "NexGenAI presents a compelling investment opportunity in the rapidly growing enterprise AI automation market. The company's proprietary algorithms offer significant performance advantages, reducing training time by 70% while maintaining accuracy.",
    cid: "bafysimexample123456789abcdefghijklmnopqrstuvwxyz",
    confidence: 78,
    metadata: JSON.stringify({
      "startup_name": "NexGenAI",
      "sector": "Artificial Intelligence",
      "stage": "Series A",
      "risk_score": 58
    }, null, 2)
  };
  
  function loadExample() {
    title = exampleData.title;
    summary = exampleData.summary;
    cid = exampleData.cid;
    confidence = exampleData.confidence;
    metadata = exampleData.metadata;
  }
  
  async function handleSubmit() {
    error = null;
    
    // Validation
    if (!title.trim()) {
      error = 'Title is required';
      return;
    }
    
    if (!summary.trim()) {
      error = 'Summary is required';
      return;
    }
    
    if (!cid.trim()) {
      error = 'IPFS CID is required';
      return;
    }
    
    if (confidence < 0 || confidence > 100) {
      error = 'Confidence must be between 0 and 100';
      return;
    }
    
    let metadataObj = {};
    if (metadata.trim()) {
      try {
        metadataObj = JSON.parse(metadata);
      } catch (e) {
        error = 'Metadata must be valid JSON';
        return;
      }
    }
    
    try {
      submitting = true;
      
      const proposalData = {
        title: title.trim(),
        summary: summary.trim(),
        cid: cid.trim(),
        confidence: parseInt(confidence),
        metadata: metadataObj
      };
      
      await proposalAPI.submitMemo(proposalData);
      
      alert('Proposal submitted successfully!');
      
      // Reset form
      title = '';
      summary = '';
      cid = '';
      confidence = 75;
      metadata = '';
      
      // Navigate back to dashboard
      dispatch('back');
      
    } catch (e) {
      error = 'Failed to submit proposal: ' + e.message;
      console.error('Error submitting proposal:', e);
    } finally {
      submitting = false;
    }
  }
  
  function goBack() {
    dispatch('back');
  }
</script>

<div class="space-y-6 animate-fade-in">
  <!-- Header -->
  <div class="flex justify-between items-center">
    <div>
      <h1 class="font-display text-4xl font-bold text-pe-text">Create Proposal</h1>
      <p class="text-pe-muted mt-2">Submit a new investment memo to the DAO</p>
    </div>
    
    <button class="flex items-center gap-2 px-4 py-2 rounded-pe text-pe-muted hover:text-pe-text hover:bg-pe-card transition-colors focus-ring" on:click={goBack}>
      <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7" />
      </svg>
      Back
    </button>
  </div>
  
  <!-- Info Alert -->
  <div class="flex items-start gap-4 p-4 rounded-pe-lg bg-pe-accent/10 border border-pe-accent/20">
    <svg class="w-6 h-6 text-pe-accent flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
      <path stroke-linecap="round" stroke-linejoin="round" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
    <div class="flex-1">
      <h3 class="font-semibold text-pe-text">Demo Mode</h3>
      <p class="text-sm text-pe-muted mt-1">
        In production, proposals are automatically generated by the SpoonOS agent. 
        This form simulates what the agent would submit.
        <button class="ml-2 px-3 py-1 rounded-pe bg-pe-accent text-white text-xs font-medium hover:bg-pe-accent-hover transition-colors" on:click={loadExample}>
          Load Example
        </button>
      </p>
    </div>
  </div>
  
  {#if error}
    <div class="flex items-start gap-4 p-4 rounded-pe-lg bg-red-500/10 border border-red-500/20">
      <svg class="w-6 h-6 text-red-500 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
        <path stroke-linecap="round" stroke-linejoin="round" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <span class="text-red-400">{error}</span>
    </div>
  {/if}
  
  <!-- Form -->
  <div class="card-pe p-6">
    <form on:submit|preventDefault={handleSubmit} class="space-y-6">
      <!-- Title -->
      <div>
        <label class="flex items-center justify-between mb-2" for="title">
          <span class="text-sm font-medium text-pe-text">Proposal Title</span>
          <span class="text-xs text-red-400">*</span>
        </label>
        <input 
          type="text" 
          id="title"
          placeholder="Investment Memo: Company Name" 
          class="search-input-pe" 
          bind:value={title}
          required
        />
      </div>
      
      <!-- Summary -->
      <div>
        <label class="flex items-center justify-between mb-2" for="summary">
          <span class="text-sm font-medium text-pe-text">Executive Summary</span>
          <span class="text-xs text-red-400">*</span>
        </label>
        <textarea 
          id="summary"
          class="search-input-pe min-h-[120px] resize-y" 
          placeholder="Brief summary of the investment opportunity..."
          bind:value={summary}
          required
        ></textarea>
        <p class="text-xs text-pe-text-dim mt-1">{summary.length} characters</p>
      </div>
      
      <!-- IPFS CID -->
      <div>
        <label class="flex items-center justify-between mb-2" for="cid">
          <span class="text-sm font-medium text-pe-text">IPFS CID</span>
          <span class="text-xs text-red-400">*</span>
        </label>
        <input 
          type="text" 
          id="cid"
          placeholder="bafysim..."
          class="search-input-pe font-mono text-sm" 
          bind:value={cid}
          required
        />
        <p class="text-xs text-pe-text-dim mt-1">The IPFS CID of the full investment memo PDF</p>
      </div>
      
      <!-- Confidence Score -->
      <div>
        <label class="flex items-center justify-between mb-2" for="confidence">
          <span class="text-sm font-medium text-pe-text">Confidence Score (0-100)</span>
          <span class="text-sm font-semibold text-pe-accent">{confidence}/100</span>
        </label>
        <input 
          type="range" 
          id="confidence"
          min="0" 
          max="100" 
          bind:value={confidence}
          class="w-full" 
          step="5"
        />
        <div class="flex justify-between text-xs text-pe-text-dim mt-2">
          <span>0</span>
          <span>25</span>
          <span>50</span>
          <span>75</span>
          <span>100</span>
        </div>
      </div>
      
      <!-- Metadata (Optional) -->
      <div>
        <label class="flex items-center justify-between mb-2" for="metadata">
          <span class="text-sm font-medium text-pe-text">Metadata (Optional JSON)</span>
          <span class="text-xs text-pe-muted">Optional</span>
        </label>
        <textarea 
          id="metadata"
          class="search-input-pe font-mono text-sm min-h-[120px] resize-y" 
          placeholder={`{"sector": "tech", "stage": "series-a", "risk_score": 50}`}
          bind:value={metadata}
        ></textarea>
        <p class="text-xs text-pe-text-dim mt-1">Additional metadata in JSON format</p>
      </div>
      
      <!-- Submit Button -->
      <div class="flex items-center justify-end gap-4 pt-4 border-t border-pe-border">
        <button 
          type="button" 
          class="px-5 py-2.5 rounded-pe text-pe-muted hover:text-pe-text hover:bg-pe-card-hover transition-colors"
          on:click={goBack}
        >
          Cancel
        </button>
        
        <button 
          type="submit" 
          class="btn-accent-pe flex items-center gap-2"
          disabled={submitting}
        >
          {#if submitting}
            <div class="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
            Submitting...
          {:else}
            <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
            </svg>
            Submit Proposal
          {/if}
        </button>
      </div>
    </form>
  </div>
</div>

<style>
  textarea {
    font-family: inherit;
  }
  
  textarea.font-mono {
    font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;
  }
</style>
