<script>
  import { createEventDispatcher } from 'svelte';
  import { proposalAPI } from '../lib/api.js';
  
  const dispatch = createEventDispatcher();
  
  let title = '';
  let summary = '';
  let cid = '';
  let confidence = 75;
  let metadata = '';
  let submitting = false;
  let error = null;
  
  // Example data for demo
  const exampleData = {
    title: "Investment Memo: NexGenAI",
    summary: "NexGenAI presents a compelling investment opportunity in the rapidly growing enterprise AI automation market. The company's proprietary algorithms offer significant performance advantages, reducing training time by 70% while maintaining accuracy.",
    cid: "bafybeiexample123456789abcdefghijklmnopqrstuvwxyz",
    confidence: 78,
    metadata: JSON.stringify({
      "startup_name": "NexGenAI",
      "sector": "Artificial Intelligence",
      "stage": "Series A",
      "risk_score": 58
    }, null, 2)
  };
  
  function loadExample() {
    title = exampleData.title;
    summary = exampleData.summary;
    cid = exampleData.cid;
    confidence = exampleData.confidence;
    metadata = exampleData.metadata;
  }
  
  async function handleSubmit() {
    error = null;
    
    // Validation
    if (!title.trim()) {
      error = 'Title is required';
      return;
    }
    
    if (!summary.trim()) {
      error = 'Summary is required';
      return;
    }
    
    if (!cid.trim()) {
      error = 'IPFS CID is required';
      return;
    }
    
    if (confidence < 0 || confidence > 100) {
      error = 'Confidence must be between 0 and 100';
      return;
    }
    
    let metadataObj = {};
    if (metadata.trim()) {
      try {
        metadataObj = JSON.parse(metadata);
      } catch (e) {
        error = 'Metadata must be valid JSON';
        return;
      }
    }
    
    try {
      submitting = true;
      
      const proposalData = {
        title: title.trim(),
        summary: summary.trim(),
        cid: cid.trim(),
        confidence: parseInt(confidence),
        metadata: metadataObj
      };
      
      await proposalAPI.submitMemo(proposalData);
      
      alert('Proposal submitted successfully!');
      
      // Reset form
      title = '';
      summary = '';
      cid = '';
      confidence = 75;
      metadata = '';
      
      // Navigate back to dashboard
      dispatch('back');
      
    } catch (e) {
      error = 'Failed to submit proposal: ' + e.message;
      console.error('Error submitting proposal:', e);
    } finally {
      submitting = false;
    }
  }
  
  function goBack() {
    dispatch('back');
  }
</script>

<div class="space-y-6">
  <!-- Header -->
  <div class="flex justify-between items-center">
    <div>
      <h1 class="text-4xl font-bold">Create Proposal</h1>
      <p class="text-gray-600 mt-2">Submit a new investment memo to the DAO</p>
    </div>
    
    <button class="btn btn-ghost" on:click={goBack}>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
      </svg>
      Back
    </button>
  </div>
  
  <!-- Info Alert -->
  <div class="alert alert-info">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current shrink-0 w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
    </svg>
    <div>
      <h3 class="font-bold">Demo Mode</h3>
      <div class="text-sm">
        In production, proposals are automatically generated by the SpoonOS agent. 
        This form simulates what the agent would submit.
        <button class="btn btn-xs btn-primary ml-2" on:click={loadExample}>Load Example</button>
      </div>
    </div>
  </div>
  
  {#if error}
    <div class="alert alert-error">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <span>{error}</span>
    </div>
  {/if}
  
  <!-- Form -->
  <div class="card bg-base-100 shadow-xl">
    <div class="card-body">
      <form on:submit|preventDefault={handleSubmit} class="space-y-4">
        <!-- Title -->
        <div class="form-control">
          <label class="label" for="title">
            <span class="label-text font-semibold">Proposal Title</span>
            <span class="label-text-alt text-error">*</span>
          </label>
          <input 
            type="text" 
            id="title"
            placeholder="Investment Memo: Company Name" 
            class="input input-bordered w-full" 
            bind:value={title}
            required
          />
        </div>
        
        <!-- Summary -->
        <div class="form-control">
          <label class="label" for="summary">
            <span class="label-text font-semibold">Executive Summary</span>
            <span class="label-text-alt text-error">*</span>
          </label>
          <textarea 
            id="summary"
            class="textarea textarea-bordered h-32" 
            placeholder="Brief summary of the investment opportunity..."
            bind:value={summary}
            required
          ></textarea>
          <label class="label">
            <span class="label-text-alt">{summary.length} characters</span>
          </label>
        </div>
        
        <!-- IPFS CID -->
        <div class="form-control">
          <label class="label" for="cid">
            <span class="label-text font-semibold">IPFS CID</span>
            <span class="label-text-alt text-error">*</span>
          </label>
          <input 
            type="text" 
            id="cid"
            placeholder="bafybei..." 
            class="input input-bordered w-full font-mono text-sm" 
            bind:value={cid}
            required
          />
          <label class="label">
            <span class="label-text-alt">The IPFS CID of the full investment memo PDF</span>
          </label>
        </div>
        
        <!-- Confidence Score -->
        <div class="form-control">
          <label class="label" for="confidence">
            <span class="label-text font-semibold">Confidence Score (0-100)</span>
            <span class="label-text-alt">{confidence}/100</span>
          </label>
          <input 
            type="range" 
            id="confidence"
            min="0" 
            max="100" 
            bind:value={confidence}
            class="range range-primary" 
            step="5"
          />
          <div class="w-full flex justify-between text-xs px-2 mt-2">
            <span>0</span>
            <span>25</span>
            <span>50</span>
            <span>75</span>
            <span>100</span>
          </div>
        </div>
        
        <!-- Metadata (Optional) -->
        <div class="form-control">
          <label class="label" for="metadata">
            <span class="label-text font-semibold">Metadata (Optional JSON)</span>
            <span class="label-text-alt">Optional</span>
          </label>
          <textarea 
            id="metadata"
            class="textarea textarea-bordered font-mono text-sm h-32" 
            placeholder='{"sector": "tech", "stage": "series-a", "risk_score": 50}'
            bind:value={metadata}
          ></textarea>
          <label class="label">
            <span class="label-text-alt">Additional metadata in JSON format</span>
          </label>
        </div>
        
        <!-- Submit Button -->
        <div class="card-actions justify-end mt-6">
          <button 
            type="button" 
            class="btn btn-ghost"
            on:click={goBack}
          >
            Cancel
          </button>
          
          <button 
            type="submit" 
            class="btn btn-primary"
            disabled={submitting}
          >
            {#if submitting}
              <span class="loading loading-spinner"></span>
              Submitting...
            {:else}
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
              </svg>
              Submit Proposal
            {/if}
          </button>
        </div>
      </form>
    </div>
  </div>
  
  <!-- How it works -->
  <div class="card bg-base-100 shadow-xl">
    <div class="card-body">
      <h2 class="card-title">How It Works</h2>
      <div class="space-y-2 text-sm">
        <div class="flex items-start gap-2">
          <div class="badge badge-primary">1</div>
          <p><strong>SpoonOS Agent:</strong> The AI agent analyzes startup data and generates a comprehensive investment memo</p>
        </div>
        <div class="flex items-start gap-2">
          <div class="badge badge-primary">2</div>
          <p><strong>PDF Generation:</strong> The memo is rendered as a professional PDF with SWOT analysis, risk assessment, and recommendations</p>
        </div>
        <div class="flex items-start gap-2">
          <div class="badge badge-primary">3</div>
          <p><strong>IPFS Upload:</strong> The PDF is uploaded to IPFS for permanent, decentralized storage</p>
        </div>
        <div class="flex items-start gap-2">
          <div class="badge badge-primary">4</div>
          <p><strong>Blockchain Submission:</strong> The proposal is submitted to the NEO smart contract and stored in the backend database</p>
        </div>
        <div class="flex items-start gap-2">
          <div class="badge badge-primary">5</div>
          <p><strong>DAO Voting:</strong> DAO members review the memo and vote on whether to invest</p>
        </div>
      </div>
    </div>
  </div>
</div>

